[package]
name = "md-notes-filter"
version = "0.1.0"
edition = "2021"
authors = ["Mo Mobarak <mo@mobarak.com>"]
description = "Filter markdown notes by tags"
license = "MIT"
repository = "https://github.com/mmobarak/md-notes-filter"

[dependencies]
clap = { version = "4.x", features = ["derive"] }